<h2>Agregar vehículo</h2>
<form action="add" method="POST" enctype="multipart/form-data">
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="marca" id="" placeholder="Marca">
    </div>
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="modelo" id="" placeholder="Modelo">
    </div>
    <div class="input-group mb-3">
        <input type="numero" class="form-control" name="anio" id="" placeholder="Año">
    </div>

    <div class="input-group mb-3">
        <input type="numero" class="form-control" name="km" id="" placeholder="Kilómetros">
    </div>
    <div class="input-group mb-3">
        <input type="numero" class="form-control" name="precio" id="" placeholder="Valor">
    </div>
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="patente" id="" placeholder="Patente">
    </div>
    <div class="input-group mb-3">
        <input type="file" class="form-control" name="imagen" id="imagen" accept="image/*" placeholder="Ingrese imagen">
    </div>
    <button type="submit" class="btn btn-success">Añadir</button>
        <!-- <a href="agregar"><input type="button" value="Añadir" class="btn btn-success"></a> -->
</form>
