<h2>Modificar vehículo</h2>
<form action="modificarModelo" method="POST" enctype="multipart/form-data">
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="marca" id="" placeholder="Marca">
    </div>
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="modelo" id="" placeholder="Modelo">
    </div>
    <div class="input-group mb-3">
        <input type="numero" class="form-control" name="anio" id="" placeholder="Año">
    </div>
    <div class="input-group mb-3">
        <input type="numero" class="form-control" name="km" id="" placeholder="Kilómetros">
        <input type="checkbox" name="es_nuevo" value="1">Es 0km        
    </div>
    <div class="input-group mb-3">
        <input type="numero" class="form-control" name="precio" id="" placeholder="Valor">
    </div>
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="patente" id="" placeholder="Patente (opcional)">
    </div>
    <div class="input-group mb-3">
        <input type="url" class="form-control" name="imagen" id="imagen" placeholder="Ingrese URL de imagen">
    </div>
    <button type="submit" class="btn btn-success">Añadir</button>
</form>
