<form action="/action_page.php" method="POST">
    <label for="marca">Marca:</label>
    <select name="cars" id="cars" class="form-select" aria-label="Default select example">
        <option value="">Seleccione una marca</option>
        <optgroup label="EE.UU">
            <option value="ford">Ford</option>
            <option value="chevrolet">Chevrolet</option>
            <option value="jeep">Jeep</option>
        </optgroup>
        <optgroup label="Japón">
            <option value="toyota">Toyota</option>
            <option value="mitsubishi">Mitsubishi</option>
        </optgroup>
        <optgroup label="Francia">
            <option value="citroen">Citroën</option>
            <option value="renault">Renault</option>
            <option value="peugeot">Peugeot</option>
        </optgroup>
        <optgroup label="Alemania">
            <option value="volkswagen">Volkswagen</option>
            <option value="audi">Audi</option>
            <option value="bmw">BMW</option>
        </optgroup>
        <optgroup label="Italia">
            <option value="fiat">Fiat</option>
            <option value="alfa">Alfa Romeo</option>
        </optgroup>
    </select>
    <br><br>
    <input type="submit" value="Mostrar">
</form>

