<!DOCTYPE html>
<html lang="es">
<head>
    <base href="<?php echo BASE_URL ?>">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title>TPE1</title>
</head>
<body>
    <header class="header">
        <h1 class="title">Concesionaria de vehículos</h1>
        <div id="logo">
            <a href="home"><img src="./img/logo_m&m.png" alt="logo de m&m"></a>
        </div>
        <nav class="navBar">
            <ul>
                <li><a href="marcas">Marcas</a></li>
                <li><a href="modelos">Modelos</a></li>
                <p>*MAIN*</p>
                
                <?php 
                if ($user): ?>
                    <li><a href="salir">salir</a></li>
                <?php else: ?>
                    <li><a href="login">iniciar sesion</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </header>
    