<section>
    <h4><?php echo $modelo->modelo ?></h4>
    <a href="<?php echo $modelo->imagen ?>"><img src="<?php echo $modelo->imagen ?>" alt="imagen del modelo"></a>
    <h6><?php echo 'Modelo ' . $modelo->anio ?></h6>
    <!-- <h6><?php echo $modelo->patente ?></h6> -->
    <!-- <h5><?php echo number_format($modelo->km, 0, '.', '.') . ' km.' ?></h5> -->
    <h2><?php echo '$ ' . number_format($modelo->precio, 0, ',', '.'); ?></h2>
    <?php if (!$modelo->vendido) { ?><a href="vendido/<?php echo $modelo->id ?>" type="button" name="comprar" class="btn btn-danger">Comprar</a> <?php }
    if ($modelo->vendido) {
        echo '<h1>¡Vendido!</h1>';
    } else {
    ?><a href="detalles/<?php echo $modelo->id ?>" type="button" name="detalles" class="btn btn-danger">Detalles</a>
    <?php } ?>
    <br>
</section>
